# Config file for camera_is1500_node
# Attention to set the right parameter here


# Placement of the camera in x-axis
# Assumption : only change in x direction
l_camera_x: 0.85 # here for et1 #distance of the camera from the center of the robot in x-axis
l_camera_y: 0.0 # distance of the camera from the center of the robot in y-axis

# Number of the needed map
mapNumber: 0
# 0: back_hangar_outside_monday_1
# 1: back_Hangar_outside_Friday_1
tableMapPaths: [/home/jonathan/Documents/wrapperCameraIS-1500/IS-1500_Software/Linux/Maps/back_hangar_outside_monday_1/environmentPSEs.cfg,
  /home/jonathan/Documents/wrapperCameraIS-1500/IS-1500_Software/Linux/Maps/back_Hangar_outside_Friday_1/environmentPSEs.cfg]
# Position of the camera origin in world GPS coordinate frame (UTM)
tableOriginX: [468589.12, 0.0]
tableOriginY: [5264024.62, 0.0]
tableRotationAngleCamToUTM: [-0.296706, 0.0]
